# Generated by Django 4.2.7 on 2025-11-06 22:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cobertura',
                'verbose_name_plural': 'Coberturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('coberturas', models.ManyToManyField(blank=True, related_name='medicos', to='turnos.cobertura')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=200)),
                ('numero_afiliado', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C')], default='A', max_length=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cobertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='turnos.cobertura')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(blank=True, help_text='Para turnos sin registro', max_length=200)),
                ('paciente_telefono', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='turnos.medico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='turnos.paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', '-hora'],
                'unique_together': {('medico', 'fecha', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_turno', models.IntegerField(help_text='Duración en minutos (15-120)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)])),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='turnos.medico')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('medico', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
