# Generated by Django 6.0.3 on 2026-04-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='turno',
            name='notas_secretaria',
            field=models.TextField(blank=True, help_text='Notas internas de la secretaria'),
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente_apellido',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ArchivoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='turnos_archivos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='turnos.turno')),
            ],
        ),
    ]
