# Generated by Django 6.0.3 on 2026-04-03 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_allow_null_fechas_turno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente_email',
            field=models.EmailField(blank=True, help_text='Email para notificaciones', max_length=254),
        ),
        migrations.CreateModel(
            name='CancelacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(default='Licencia parcial', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones_horario', to='turnos.medico')),
            ],
            options={
                'verbose_name': 'Cancelación de Horario',
                'verbose_name_plural': 'Cancelaciones de Horarios',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CancelacionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(default='Feriado/Licencia', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones_dia', to='turnos.medico')),
            ],
            options={
                'verbose_name': 'Cancelación de Día',
                'verbose_name_plural': 'Cancelaciones de Días',
                'unique_together': {('medico', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Sobreturno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=200)),
                ('paciente_apellido', models.CharField(max_length=200)),
                ('paciente_telefono', models.CharField(max_length=20)),
                ('paciente_email', models.EmailField(blank=True, max_length=254)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField(blank=True)),
                ('notas_secretaria', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobreturnos', to='turnos.medico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sobreturnos', to='turnos.paciente')),
            ],
            options={
                'verbose_name': 'Sobreturno',
                'verbose_name_plural': 'Sobreturnos',
                'ordering': ['-fecha', '-hora'],
                'unique_together': {('medico', 'fecha', 'hora')},
            },
        ),
    ]
