# Generated by Django 6.0.3 on 2026-04-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_nuevos_modelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
